- name: "manage server1"
  hosts: all
  become: true
  tasks:

          - name:  "Clone a github repository"
            git:
                    repo: https://github.com/vaadin/addressbook
                    dest: /home/ubuntu/addressbook/
                    clone: yes
                    update: yes
                    
          - name:  "install maven"
            apt: pkg=maven state=latest update_cache=yes cache_valid_time=3600



