- name: "manage server1"
  hosts: server1
  become: true
  tasks:

          - name:  "Clone a github repository"
            git:
                    repo: https://github.com/vaadin/addressbook
                    dest: /home/ubuntu/repo/
                    clone: yes
                    update: yes
          - name:  "install maven"
            apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
            with_items:
                   - maven

          - name: "Compile"
            command: mvn compile
      
