- name: "manage server1"
  hosts: server1
  become: true
  tasks:
  
            - name:  "Clone a github repository"
              git:
                    repo: https://github.com/vaadin/addressbook
                    dest: /home/ubuntu/addressbook/
                    clone: yes
                    update: yes
                    
            
            - name:  "install tomcat"
              apt: pkg=tomcat9 state=latest update_cache=yes cache_valid_time=3600
            
            - name:  "copy file"
              copy:
                    src: /home/ubuntu/addressbook/target/addressbook-2.0.war
                    dest: /var/lib/tomcat9/webapps/addressbook3.war
                    remote_src: yes
              notify: "restart tomcat"               
  handlers:
            - name:   "restart tomcat"
              service:
                       name: tomcat9
                       state: restarted
                       enabled: yes




