- name: "manage server1"
  hosts: server1
  become: true
  tasks:

          - name:  "Clone a github repository"
            git:
                    repo: https://github.com/vaadin/addressbook
                    dest: /home/ubuntu/repo/
                    clone: yes
                    update: yes

          - name: "install maven"
            apt:
                    name: maven
                    state: present
                    update_cache: yes

          - name: "Compile"
            command: mvn compile
      
