- name: "manage server1"
  hosts: all
  become: true
  tasks:
            
          - name:  "copy"
            copy:
                 src: /home/ubuntu/addressbook/target/addressbook-2.0.war
                 dest: /var/lib/tomcat9/webapps/addressbook.war
                 remote_src: yes


